export default {
  login: "amirhazizi",
  id: 122512384,
  node_id: "U_kgDOB01kAA",
  avatar_url: "https://avatars.githubusercontent.com/u/122512384?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/amirhazizi",
  html_url: "https://github.com/amirhazizi",
  followers_url: "https://api.github.com/users/amirhazizi/followers",
  following_url:
    "https://api.github.com/users/amirhazizi/following{/other_user}",
  gists_url: "https://api.github.com/users/amirhazizi/gists{/gist_id}",
  starred_url: "https://api.github.com/users/amirhazizi/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/amirhazizi/subscriptions",
  organizations_url: "https://api.github.com/users/amirhazizi/orgs",
  repos_url: "https://api.github.com/users/amirhazizi/repos",
  events_url: "https://api.github.com/users/amirhazizi/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/amirhazizi/received_events",
  type: "User",
  site_admin: false,
  name: "Amirhossein",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 52,
  public_gists: 0,
  followers: 2,
  following: 3,
  created_at: "2023-01-12T06:04:50Z",
  updated_at: "2023-02-09T15:52:27Z",
}
